const subdomain = window.location.host.split('.')[1] ? window.location.host.split('.')[0] : false;
export const baseApiUrl = `http://backend1.host.local/api`;
//\export const baseApiUrl = `https://b-${subdomain}.ttmlive.com/api`;
export const autoLoginTime = process.env.NODE_ENV === 'dev' ? 9000000 : 400000;
export const roles = {
    ADMIN: 'SA',
    GERENTE: 'Gerente'
}

export const authorities = {
    DASHBOARD_VIEW: "dashboard-view",
    SETTINGS_VIEW: "setting-view",
    SETTINGS_EDIT: "setting-edit",
    ROLE_VIEW: "role-view",
    ROLE_CREATE: "role-create",
    ROLE_EDIT: "role-edit",
    ROLE_DELETE: "role-delete",
    USER_VIEW: "user-view",
    USER_CREATE: "user-create",
    USER_EDIT: "user-edit",
    USER_DELETE: "user-delete",
    BUSINESS_VIEW: "business-view",
    BUSINESS_CREATE: "business-create",
    BUSINESS_EDIT: "business-edit",
    BUSINESS_DELETE: "business-delete",
    CUSTOMER_VIEW: "customer-view",
    CUSTOMER_CREATE: "customer-create",
    CUSTOMER_EDIT: "customer-edit",
    CUSTOMER_DELETE: "customer-delete",
    LOAN_TRANSACTION_VIEW: "loan_transaction-view",
    LOAN_TRANSACTION_CREATE: "loan_transaction-create",
    LOAN_TRANSACTION_EDIT: "loan_transaction-edit",
    LOAN_TRANSACTION_DELETE: "loan_transaction-delete",
    LOAN_VIEW: "loan-view",
    LOAN_CREATE: "loan-create",
    LOAN_EDIT: "loan-edit",
    LOAN_DELETE: "loan-delete",
    LOAN_SIMULATE: "loan-simulate",
    LOAN_APPROVE: "loan-approve",
    LOAN_DISBURSE: "loan-disburse",
    LOAN_RESTRUCT: "loan-restruct",
    LOAN_CLOSE: "loan-close",
    ACCOUNT_VIEW: "account-view",
    ACCOUNT_CREATE: "account-create",
    ACCOUNT_EDIT: "account-edit",
    ACCOUNT_DELETE: "account-delete",
    MANAGER_VIEW: "manager-view",
    MANAGER_CREATE: "manager-create",
    MANAGER_EDIT: "manager-edit",
    MANAGER_DELETE: "manager-delete",
    WARRANTY_VIEW: "warranty-view",
    WARRANTY_CREATE: "warranty-create",
    WARRANTY_EDIT: "warranty-edit",
    WARRANTY_DELETE: "warranty-delete",
    CREDIT_TYPE_VIEW: "credit_type-view",
    CREDIT_TYPE_CREATE: "credit_type-create",
    CREDIT_TYPE_EDIT: "credit_type-edit",
    CREDIT_TYPE_DELETE: "credit_type-delete",
    DOCUMENT_VIEW: "document-view",
    DOCUMENT_CREATE: "document-create",
    DOCUMENT_EDIT: "document-edit",
    DOCUMENT_DELETE: "document-delete"
}
